### ISSUE TITLE
Reminder: Android SDK setup broken on GH Actions Ubuntu 20.04

### ISSUE THREAD

**Issue by floooh** [floooh/sokol#480]
The GH Actions Linux VMs have switched to Ubuntu 20.04 which broke the fips Android SDK setup:

```
Cloning into 'sokol-samples'...
Cloning into '/home/runner/work/sokol/sokol/workspace/fips'...
=== cloning fips build system to '/home/runner/work/sokol/sokol/workspace/fips':
=== setup Android SDK/NDK :
[ERROR] please install Java JDK 8 (see './fips diag tools')
yes: standard output: Broken pipe
Error: Process completed with exit code 10.
```

**Comment by floooh** [comment]
Fixed.

**Comment by tobiasherzke** [comment]
> Fixed.

Could you please share how to fix this error on Ubuntu? I have openjdk-8 and openjdk-11 installed and still get this error.

**Comment by floooh** [comment]
I don't have access to my Linux laptop this week, need to check when I'm back in Berlin next week.

What do you see when running ```javac -version``` on the terminal?

E.g. on my Mac with a JDK installed with ```brew install semeru-jdk8-open```:

```
javac -version
javac 1.8.0_345
```

**Comment by floooh** [comment]
PS: in the GH Actions workflow file I fixed it like this:

https://github.com/floooh/sokol/blob/bba1d39476abc719f8737f962d75ba590c37eeb8/.github/workflows/main.yml#L59-L61

Thet setup-java option is here:

https://github.com/actions/setup-java

...but it's a bit hard to figure out what's happening under the hood though.
